version: "3"


services:
  importer:
    build: ./importer
    volumes:
      - ./importer/input:/usr/app/input
    env_file:
    - .env

  service:
    build: ./service
    env_file:
    - .env
    depends_on:
      - db
      - importer

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
    - .env

networks:
  default:
    external:
      name: kafka-network

volumes:
  postgres_data:
